import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import '../styles/test.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='flex items-center justify-center color-yellow'>
        hello world
      </div>
    </div>
  )
}
