import Head from 'next/head'
import Image from 'next/image'
import { useDispatch, useSelector } from 'react-redux'
import { changeName } from 'redux/reducers/testSlice';
// import styles from '../styles/Home.module.css'
// import '../styles/test.scss'

export default function Home() {
  const { name } = useSelector((state) => state.demo);
  const dispatch = useDispatch();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='flex items-center justify-center color-yellow'>
        hello world {name}
      </div>

      <button onClick={() => dispatch(changeName('hoi ne'))}>click</button>
    </div>
  )
}
